### PR TITLE
Update README after renaming repo #555

### PR DESCRIPTION
**Pull request by taylor**
See https://github.com/cncf/cnf-conformance/ for conformance docs

README-testsuite renamed to README.md

See https://github.com/cncf/cnf-conformance/ for conformance program docs

ref #555

### CODE REVIEW

**Review by agentpoyo — APPROVED** [review]
LGTM

**Comment by agentpoyo** [comment]
Looks like we need to update the git clones in the GH actions, the test binaries and crystal specs all are failing after the repo name change.

@wavell @denverwilliams @taylor @lixuna @williscool

**Comment by taylor** [comment]
Add that comment to #555 as well please @agentpoyo

**Comment by taylor** [comment]
A new PR can update the GitHub actions. This one only addresses the readme

**Pull request merged**
